- name: Logging to /var/log/ufw.log
  become: true
  community.general.ufw:
    logging: "on"

- name: Set the default incoming policy (ALL deny)
  become: true
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Set the default outgoing policy (ALL allow)
  become: true
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow SSH port number
  become: true
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "22"

- name: Reloads firewall and enables firewall on boot
  become: true
  community.general.ufw:
    state: enabled
