- name: Check if the file exists
  ansible.builtin.stat:
    path: "{{ vpn_server_config }}"
  register: config_file

- name: Get vpn_server.config
  become: true
  ansible.builtin.fetch:
    src: "{{ vpn_server_config }}"
    dest: files/"{{ ansible_host }}"_vpn_server.config
    flat: yes
  when: config_file.stat.exists
