- name: Stop softether
  become: true
  ansible.builtin.service:
    name: softether
    state: stopped

- name: Copy vpn_server.config
  become: true
  ansible.builtin.copy:
    src:  files/"{{ ansible_host }}"_vpn_server.config
    dest: "{{ vpn_server_config }}"
  ignore_errors: true

- name: Start softether
  become: true
  ansible.builtin.service:
    name: softether
    state: started