- name: Allow UDP ports
  become: true
  community.general.ufw:
    rule: allow
    proto: udp
    port: "{{ item }}"
  loop: "{{ enable_udp_ports }}"

- name: Allow TCP ports
  become: true
  community.general.ufw:
    rule: allow
    proto: tcp
    port: "{{ item }}"
  loop: "{{ enable_tcp_ports }}"

